// ─── Dados estáticos do módulo de Perfil de Investidor ────────────────────────
// Carregado como <script> plain antes do Babel, expõe variáveis globais usadas
// pelos componentes InvestorProfileCard (dashboard) e ProfileResult (perfil).

const PROFILE_META = {
  CONSERVADOR: {
    icon: 'bi-shield-check', color: '#1d9e63',
    tagline: 'Segurança em primeiro lugar',
    allocation: [
      { label: 'Renda Fixa',     pct: 70, color: '#1d9e63' },
      { label: 'Fundos Mistos',  pct: 20, color: '#0891b2' },
      { label: 'Renda Variável', pct: 10, color: '#f59e0b' },
    ],
  },
  MODERADO: {
    icon: 'bi-graph-up', color: '#d97706',
    tagline: 'Crescimento com os pés no chão',
    allocation: [
      { label: 'Renda Fixa',     pct: 50, color: '#1d9e63' },
      { label: 'FIIs',           pct: 20, color: '#d97706' },
      { label: 'Renda Variável', pct: 20, color: '#e05252' },
      { label: 'Internacional',  pct: 10, color: '#8b5cf6' },
    ],
  },
  ARROJADO: {
    icon: 'bi-graph-up-arrow', color: '#e05252',
    tagline: 'Crescimento máximo no longo prazo',
    allocation: [
      { label: 'Renda Variável', pct: 50, color: '#e05252' },
      { label: 'Internacional',  pct: 20, color: '#8b5cf6' },
      { label: 'FIIs',           pct: 15, color: '#d97706' },
      { label: 'Renda Fixa',     pct: 15, color: '#1d9e63' },
    ],
  },
};

const QUESTIONS = [
  { id: 'renda_mensal', icon: 'bi-cash-coin', label: 'Qual é a sua renda mensal aproximada?',
    options: [{ v:'ate_2k', l:'Até R$ 2.000'}, {v:'2k_5k', l:'R$ 2.001 a R$ 5.000'},
              {v:'5k_10k', l:'R$ 5.001 a R$ 10.000'}, {v:'acima_10k', l:'Acima de R$ 10.000'}] },
  { id: 'gasto_mensal', icon: 'bi-receipt', label: 'Qual percentual da sua renda você gasta mensalmente?',
    options: [{v:'ate_50', l:'Até 50%'}, {v:'50_80', l:'Entre 50% e 80%'},
              {v:'80_100', l:'Entre 80% e 100%'}, {v:'acima', l:'Mais do que ganha (endividado)'}] },
  { id: 'dividas', icon: 'bi-credit-card', label: 'Você possui dívidas atualmente?',
    options: [{v:'nao', l:'Não tenho dívidas'}, {v:'sim_controle', l:'Sim, mas estão sob controle'},
              {v:'sim_pesadas', l:'Sim, e pesam no orçamento'}] },
  { id: 'objetivo', icon: 'bi-bullseye', label: 'Qual é o seu principal objetivo financeiro?',
    options: [{v:'emergencia', l:'Reserva de emergência'}, {v:'aposentadoria', l:'Aposentadoria / independência'},
              {v:'compra_bem', l:'Comprar um bem (imóvel, carro)'}, {v:'renda_extra', l:'Gerar renda passiva'}] },
  { id: 'horizonte', icon: 'bi-calendar-range', label: 'Em quanto tempo deseja atingir seu objetivo?',
    options: [{v:'curto', l:'Curto prazo (até 2 anos)'}, {v:'medio', l:'Médio prazo (2 a 5 anos)'},
              {v:'longo', l:'Longo prazo (mais de 5 anos)'}] },
  { id: 'ja_investe', icon: 'bi-bar-chart', label: 'Você já investe atualmente?',
    options: [{v:'nao', l:'Não, nunca investi'}, {v:'sim_basico', l:'Sim, apenas poupança'},
              {v:'sim_diversificado', l:'Sim, tenho investimentos diversificados'}] },
  { id: 'reacao_perdas', icon: 'bi-graph-down-arrow', label: 'Se seu investimento perdesse 20% em um mês, você:',
    options: [{v:'venderia', l:'Venderia tudo para evitar mais perdas'},
              {v:'preocupado', l:'Esperaria recuperar, mas ficaria preocupado'},
              {v:'tranquilo', l:'Aproveitaria para investir mais'}] },
  { id: 'poupanca_mensal', icon: 'bi-piggy-bank', label: 'Quanto do seu salário consegue poupar mensalmente?',
    options: [{v:'nada', l:'Nada por enquanto'}, {v:'ate_10', l:'Menos de 10%'},
              {v:'10_30', l:'Entre 10% e 30%'}, {v:'acima_30', l:'Mais de 30%'}] },
];

const PROFILE_DATA = {
  CONSERVADOR: {
    cls: 'conservador', icon: 'bi-shield-check', color: '#1d9e63',
    tagline: 'Segurança em primeiro lugar',
    desc: 'Você prefere dormir tranquilo sabendo que seu dinheiro está seguro. Para você, ganhar um pouco menos mas não correr risco de perder o que juntou com tanto esforço vale muito mais do que apostar em retornos maiores. Seu foco é proteger o patrimônio e crescer de forma previsível.',
    allocation: [
      { label: 'Renda Fixa',     pct: 70, color: '#1d9e63' },
      { label: 'Fundos Mistos',  pct: 20, color: '#0891b2' },
      { label: 'Renda Variável', pct: 10, color: '#f59e0b' },
    ],
    products: [
      { icon: 'bi-bank', name: 'Tesouro Selic', desc: 'Liquidez diária, segurança máxima', tag: 'Essencial',
        detail: 'Imagine que o governo precisa de dinheiro emprestado para pagar suas contas. Ele te pede esse empréstimo e, em troca, te devolve o valor com juros — exatamente o que a Selic (a taxa de juros oficial do Brasil) estiver pagando naquele momento. Isso é o Tesouro Selic.\n\nÉ considerado o investimento mais seguro do Brasil porque quem garante o pagamento é o próprio governo federal. Praticamente não existe risco de calote. E o melhor: você pode pedir o dinheiro de volta a qualquer dia útil, sem perder nada do que rendeu. É o lugar ideal para guardar sua reserva de emergência.',
        method: 'Abra conta em uma corretora gratuita e busque por "Tesouro Selic" na área de renda fixa. Verifique se a corretora cobra taxa de custódia — escolha sempre uma que não cobra.' },
      { icon: 'bi-building', name: 'CDB / LCI / LCA', desc: 'Proteção FGC, rendimento acima da poupança', tag: 'Recomendado',
        detail: 'CDB, LCI e LCA são formas de emprestar dinheiro para bancos — em troca, eles te pagam juros. A diferença para a poupança? O rendimento é bem maior e existe uma proteção chamada FGC que cobre até R$ 250 mil por banco caso ele quebre.\n\nLCI e LCA têm um bônus extra: são isentos de Imposto de Renda.',
        method: 'Compare as taxas em sites de comparação. Para CDBs, procure sempre taxas acima de 100% do CDI. Verifique com atenção o prazo: muitos CDBs só deixam você resgatar na data de vencimento.' },
      { icon: 'bi-shield', name: 'Tesouro IPCA+', desc: 'Proteção contra inflação no longo prazo', tag: 'Complementar',
        detail: 'O Tesouro IPCA+ paga sempre a inflação oficial (IPCA) mais uma taxa extra. Então, se a inflação for 5% no ano e o título pagar "IPCA + 6,5%", você rendeu 11,5% no total — garantindo que seu dinheiro cresceu de verdade, acima da inflação.',
        method: 'No Tesouro Direto, escolha a data mais próxima do seu objetivo. A taxa extra é o que você vai receber acima da inflação: quanto maior, melhor.' },
      { icon: 'bi-layers', name: 'Fundos DI', desc: 'Gestão profissional de renda fixa', tag: 'Complementar',
        detail: 'Um Fundo DI funciona como um "condomínio de investimentos": várias pessoas colocam dinheiro juntas, um gestor profissional investe esse dinheiro em títulos seguros e os rendimentos são divididos proporcionalmente entre todos.',
        method: 'O critério mais importante é a taxa de administração: encontre-a na lâmina do fundo. Fundos com taxa acima de 0,5% ao ano quase sempre rendem menos do que o Tesouro Selic diretamente.' },
    ],
    steps: [
      { label: 'Monte sua reserva de emergência', desc: 'Monte uma reserva de 6 meses de gastos em Tesouro Selic ou CDB com liquidez diária',
        detail: 'A reserva de emergência é o seu colchão financeiro — a quantia que você guarda para usar quando algo inesperado acontece. O ideal é ter entre 3 e 6 meses dos seus gastos mensais totais guardados em um lugar que você consegue resgatar no mesmo dia.' },
      { label: 'Busque CDBs com maior rentabilidade', desc: 'Pesquise CDBs com rentabilidade acima de 100% do CDI em bancos digitais',
        detail: 'A poupança rende cerca de 70% da Selic. Ao migrar para CDBs de bancos digitais, você pode facilmente encontrar taxas de 100% a 130% do CDI com a mesma segurança do FGC.' },
      { label: 'Abra conta em uma corretora', desc: 'Abra conta em uma corretora gratuita para acessar o Tesouro Direto sem taxa',
        detail: 'Para comprar títulos do Tesouro Direto, você precisa de uma corretora habilitada pelo Tesouro Nacional. A maioria das corretoras digitais permite abertura de conta gratuitamente e sem taxa de custódia — pesquise e compare antes de escolher.' },
      { label: 'Respeite o limite do FGC', desc: 'Não deixe mais de R$ 250 mil por banco em CDB, LCI ou LCA',
        detail: 'O FGC garante a devolução de até R$ 250 mil por CPF por instituição. Quando ultrapassar esse valor, distribua entre diferentes bancos para manter tudo protegido.' },
    ],
  },
  MODERADO: {
    cls: 'moderado', icon: 'bi-graph-up', color: '#d97706',
    tagline: 'Crescimento com os pés no chão',
    desc: 'Você entende que, para crescer mais, precisa aceitar um pouco de incerteza — mas não quer colocar tudo em risco. Sua estratégia é equilibrada: uma base sólida e segura complementada por investimentos que podem render mais, mesmo que com algumas oscilações no caminho.',
    allocation: [
      { label: 'Renda Fixa',     pct: 50, color: '#1d9e63' },
      { label: 'FIIs',           pct: 20, color: '#d97706' },
      { label: 'Renda Variável', pct: 20, color: '#e05252' },
      { label: 'Internacional',  pct: 10, color: '#8b5cf6' },
    ],
    products: [
      { icon: 'bi-shield', name: 'Tesouro IPCA+', desc: 'Base sólida que bate a inflação sempre', tag: 'Essencial',
        detail: 'O Tesouro IPCA+ garante que o seu dinheiro vai sempre render acima da inflação, preservando o seu poder de compra. Ele funciona assim: paga a inflação do período mais uma taxa extra.',
        method: 'Acesse o Tesouro Direto e escolha o título com vencimento mais próximo da data em que vai querer usar o dinheiro. Preste atenção na taxa real: quanto maior, melhor.' },
      { icon: 'bi-buildings', name: 'FIIs (Fundos Imobiliários)', desc: 'Invista em imóveis sem precisar comprar um', tag: 'Recomendado',
        detail: 'Com os FIIs você pode ser dono de um shopping, de um galpão logístico ou de um edifício de escritórios de forma indireta. O aluguel e os rendimentos são divididos entre todos os participantes todo mês, direto na sua conta de corretora.',
        method: 'Verifique o Dividend Yield anual (acima de 8% é interessante), a vacância (imóveis vazios = menos renda) e o P/VP (abaixo de 1,0 pode indicar cota barata).' },
      { icon: 'bi-pie-chart', name: 'ETFs de Índice', desc: 'Invista em todas as grandes empresas de uma vez', tag: 'Recomendado',
        detail: 'Quando você compra uma cota de um ETF que replica o principal índice da bolsa brasileira, está comprando um pedacinho de todas as maiores empresas do país ao mesmo tempo. Se uma empresa vai mal, as outras equilibram — isso se chama diversificação automática.\n\nÉ a porta de entrada mais eficiente para a renda variável: você não precisa estudar cada empresa individualmente e a taxa de administração costuma ser muito baixa.',
        method: 'Busque ETFs de índice na área de renda variável da sua corretora. O principal critério é a taxa de administração (abaixo de 0,3% ao ano). Verifique também o volume diário de negociação — quanto maior, mais fácil comprar e vender. Não tente prever o melhor momento de comprar — compre regularmente todo mês.' },
      { icon: 'bi-globe', name: 'ETFs Internacionais', desc: 'Proteja seu dinheiro contra crises locais', tag: 'Complementar',
        detail: 'Colocar parte da carteira em ETFs internacionais é como ter um "seguro geográfico" — quando o Brasil vai mal, os mercados globais nem sempre vão junto. Você passa a investir indiretamente nas maiores economias do mundo, sem precisar abrir conta no exterior.\n\nAlém de acessar empresas que não existem na bolsa brasileira, você se protege da desvalorização do real: se o dólar sobe, o valor do seu investimento em reais sobe junto.',
        method: 'Busque ETFs internacionais disponíveis na bolsa brasileira que repliquem índices globais reconhecidos. Verifique o Tracking Error (quanto menor, melhor) e o volume diário de negociação. Mantenha no máximo 10 a 20% da carteira nessa categoria.' },
    ],
    steps: [
      { label: 'Garanta a reserva de emergência primeiro', desc: 'Antes de tudo, guarde 3 a 6 meses de gastos em renda fixa com liquidez diária',
        detail: 'Antes de pensar em qualquer investimento na bolsa ou em FIIs, você precisa ter uma reserva de emergência montada. Se você investir sem ter essa reserva e surgir uma emergência, vai ser forçado a vender seus investimentos — possivelmente em queda.' },
      { label: 'Comece com ETFs para conhecer a bolsa', desc: 'ETFs de índice são a porta de entrada ideal para a renda variável',
        detail: 'A tentação de quem começa na bolsa é escolher ações específicas. Mas sem experiência, é muito fácil escolher mal e perder dinheiro. Os ETFs de índice eliminam esse problema: com uma única cota você investe automaticamente nas maiores empresas do mercado, sem precisar analisar nenhuma delas individualmente.' },
      { label: 'Pesquise FIIs com histórico sólido', desc: 'Escolha FIIs que pagam rendimentos consistentes há pelo menos 2 anos',
        detail: 'Antes de investir, verifique se aquele fundo realmente entrega o que promete ao longo do tempo. O ideal é pesquisar o histórico de distribuições mensais dos últimos 2 a 3 anos.' },
      { label: 'Invista um valor fixo todo mês', desc: 'Aportar mensalmente — mesmo pouco — é mais eficaz do que tentar adivinhar o melhor momento',
        detail: 'Defina um valor fixo (por exemplo, R$ 300 por mês) e invista todo mês, independente do que o mercado estiver fazendo. Quando os preços estão baixos, o mesmo dinheiro compra mais cotas.' },
    ],
  },
  ARROJADO: {
    cls: 'arrojado', icon: 'bi-graph-up-arrow', color: '#e05252',
    tagline: 'Crescimento máximo no longo prazo',
    desc: 'Você entende que as maiores recompensas vêm para quem aceita os maiores riscos — e tem estômago para isso. Quando o mercado cai, você não entra em pânico: sabe que oscilações fazem parte do jogo e que o longo prazo favorece quem mantém a cabeça fria.',
    allocation: [
      { label: 'Renda Variável', pct: 50, color: '#e05252' },
      { label: 'Internacional',  pct: 20, color: '#8b5cf6' },
      { label: 'FIIs',           pct: 15, color: '#d97706' },
      { label: 'Renda Fixa',     pct: 15, color: '#1d9e63' },
    ],
    products: [
      { icon: 'bi-graph-up-arrow', name: 'Ações (B3)', desc: 'Seja sócio das maiores empresas do Brasil', tag: 'Essencial',
        detail: 'Quando você compra uma ação, você se torna sócio daquela empresa. Se ela lucrar, você lucra. As ações oscilam bastante no dia a dia — isso é normal. Mas no longo prazo, as empresas boas tendem a crescer e os preços sobem.',
        method: 'Verifique P/L, ROE (acima de 15% é bom), Dívida Líquida/EBITDA (abaixo de 2x) e Margem Líquida. Compare sempre com outras empresas do mesmo setor.' },
      { icon: 'bi-globe2', name: 'ETFs Globais', desc: 'Invista nas maiores empresas do mundo pela bolsa brasileira', tag: 'Recomendado',
        detail: 'Com ETFs que replicam índices globais, você investe indiretamente nas maiores empresas do mundo diretamente pela bolsa brasileira, sem precisar abrir conta no exterior. Além de acessar economias que não existem aqui, você se protege da desvalorização do real: se o dólar sobe, o valor em reais do seu investimento sobe junto.',
        method: 'Pesquise ETFs internacionais disponíveis na bolsa brasileira que referenciem índices globais reconhecidos. Verifique o Tracking Error (o quanto o ETF desvia do índice original): abaixo de 1% ao ano é bom. Observe o volume diário de negociação — ETFs com volume baixo têm maior custo de compra e venda.' },
      { icon: 'bi-buildings', name: 'FIIs', desc: 'Renda mensal que equilibra a volatilidade da carteira', tag: 'Recomendado',
        detail: 'Mesmo sendo um investidor arrojado, ter 15% da carteira em FIIs faz sentido: enquanto as ações podem não pagar nada por meses, os FIIs jogam dinheiro na sua conta todo mês. Esse rendimento pode ser reinvestido.',
        method: 'Para o perfil Arrojado, dê preferência a FIIs mais agressivos: FIIs de desenvolvimento e FIIs de papel com CRIs de alta rentabilidade.' },
      { icon: 'bi-currency-bitcoin', name: 'Criptoativos', desc: 'Alto risco, alto potencial — mantenha pequeno', tag: 'Opcional',
        detail: 'Criptomoedas podem subir centenas de por cento em um ano — ou cair 70% em alguns meses. Essa volatilidade extrema é tanto o apelo quanto o maior perigo. Para o perfil Arrojado, uma exposição de até 5% do patrimônio faz sentido como uma aposta de alto potencial.\n\nSe valorizar muito, melhora o resultado geral da carteira sem que você tenha sacrificado o restante. Se desvalorizar, o impacto é limitado. A regra de ouro: nunca invista em criptoativos um valor que, se fosse a zero, comprometeria seus objetivos de vida.',
        method: 'Prefira as criptomoedas mais antigas e com maior capitalização de mercado, pois tendem a ser mais líquidas e menos suscetíveis a manipulação. A forma regulamentada de investir no Brasil é por meio de ETFs de criptoativos negociados na bolsa, que dispensam o gerenciamento de carteiras digitais. Fuja de projetos sem equipe identificada, sem documentação técnica pública ou que prometem retornos garantidos — esses são sinais quase certos de golpe.' },
    ],
    steps: [
      { label: 'Mantenha a reserva de emergência separada', desc: 'Guarde pelo menos 3 meses de gastos em renda fixa líquida, fora da carteira de investimentos',
        detail: 'Mesmo sendo arrojado, você não pode misturar a reserva de emergência com a carteira de investimentos. Se o mercado cai exatamente quando você perde o emprego, você precisaria vender ativos no pior momento.' },
      { label: 'Aprenda a analisar empresas antes de comprar ações', desc: 'Entender o básico de análise fundamentalista separa o investidor do especulador',
        detail: 'Análise fundamentalista é o método de entender se uma empresa vale o que está sendo cobrado. Os principais "documentos" são os relatórios trimestrais de resultado (ITR), disponíveis no site da B3.' },
      { label: 'Invista um valor fixo todo mês, sem exceção', desc: 'Aportes mensais regulares superam qualquer tentativa de acertar o melhor momento do mercado',
        detail: 'Invista um valor fixo todo mês, independente do mercado (Dollar-Cost Averaging). Quando as ações caem, o mesmo dinheiro compra mais cotas. No longo prazo, isso resulta em custo médio menor.' },
      { label: 'Distribua entre setores e países diferentes', desc: 'Não concentre toda a carteira em um setor ou país — diversificação é proteção',
        detail: 'Distribua entre setores diferentes (tecnologia, energia, saúde, consumo, financeiro) e entre países diferentes (Brasil + EUA + global). Quanto mais distribuído, menos você depende de uma única aposta dar certo.' },
    ],
  },
};
