-- ============================================================
-- SEED - PragFY
-- Dados iniciais para desenvolvimento e demonstração
-- Mês de referência: Maio / 2026
-- ============================================================


-- ── Usuário de demonstração ───────────────────────────────────
INSERT INTO TB_USUARIOS (DS_NOME, DS_EMAIL, DS_SENHA, DT_REGISTRO)
VALUES ('Diego', 'diego@pragfy.com', '123456', CURRENT_TIMESTAMP);


-- ── Categorias de Receita ─────────────────────────────────────
INSERT INTO TB_CATEGORIAS (ID_USUARIO, DS_NOME, CD_TIPO, DS_COR, DS_ICONE)
VALUES ((SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com'),
        'Salário', 'RECEITA', '#1a9e5c', 'bi-briefcase');

INSERT INTO TB_CATEGORIAS (ID_USUARIO, DS_NOME, CD_TIPO, DS_COR, DS_ICONE)
VALUES ((SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com'),
        'Freelance', 'RECEITA', '#8b5cf6', 'bi-gift');

INSERT INTO TB_CATEGORIAS (ID_USUARIO, DS_NOME, CD_TIPO, DS_COR, DS_ICONE)
VALUES ((SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com'),
        'Investimentos', 'RECEITA', '#0426b0', 'bi-graph-up');


-- ── Categorias de Despesa ─────────────────────────────────────
INSERT INTO TB_CATEGORIAS (ID_USUARIO, DS_NOME, CD_TIPO, DS_COR, DS_ICONE)
VALUES ((SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com'),
        'Moradia', 'DESPESA', '#e55353', 'bi-house');

INSERT INTO TB_CATEGORIAS (ID_USUARIO, DS_NOME, CD_TIPO, DS_COR, DS_ICONE)
VALUES ((SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com'),
        'Alimentação', 'DESPESA', '#f59e0b', 'bi-cart');

INSERT INTO TB_CATEGORIAS (ID_USUARIO, DS_NOME, CD_TIPO, DS_COR, DS_ICONE)
VALUES ((SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com'),
        'Transporte', 'DESPESA', '#0891b2', 'bi-car-front');

INSERT INTO TB_CATEGORIAS (ID_USUARIO, DS_NOME, CD_TIPO, DS_COR, DS_ICONE)
VALUES ((SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com'),
        'Saúde', 'DESPESA', '#db2777', 'bi-heart-pulse');

INSERT INTO TB_CATEGORIAS (ID_USUARIO, DS_NOME, CD_TIPO, DS_COR, DS_ICONE)
VALUES ((SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com'),
        'Lazer', 'DESPESA', '#65a30d', 'bi-controller');

INSERT INTO TB_CATEGORIAS (ID_USUARIO, DS_NOME, CD_TIPO, DS_COR, DS_ICONE)
VALUES ((SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com'),
        'Serviços', 'DESPESA', '#0891b2', 'bi-lightning');


-- ── Transações — Maio 2026 ────────────────────────────────────

-- Receitas
INSERT INTO TB_TRANSACOES (ID_USUARIO, ID_CATEGORIA, VL_VALOR, DS_DESCRICAO, DT_TRANSACAO, CD_TIPO)
VALUES (
    (SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com'),
    (SELECT ID_CATEGORIA FROM TB_CATEGORIAS WHERE DS_NOME = 'Salário'
        AND ID_USUARIO = (SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com')),
    7500.00, 'Salário Maio 2026',
    TO_DATE('2026-05-05', 'YYYY-MM-DD'), 'RECEITA'
);

INSERT INTO TB_TRANSACOES (ID_USUARIO, ID_CATEGORIA, VL_VALOR, DS_DESCRICAO, DT_TRANSACAO, CD_TIPO)
VALUES (
    (SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com'),
    (SELECT ID_CATEGORIA FROM TB_CATEGORIAS WHERE DS_NOME = 'Freelance'
        AND ID_USUARIO = (SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com')),
    1200.00, 'Projeto site institucional',
    TO_DATE('2026-05-12', 'YYYY-MM-DD'), 'RECEITA'
);

-- Despesas
INSERT INTO TB_TRANSACOES (ID_USUARIO, ID_CATEGORIA, VL_VALOR, DS_DESCRICAO, DT_TRANSACAO, CD_TIPO)
VALUES (
    (SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com'),
    (SELECT ID_CATEGORIA FROM TB_CATEGORIAS WHERE DS_NOME = 'Moradia'
        AND ID_USUARIO = (SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com')),
    1800.00, 'Aluguel',
    TO_DATE('2026-05-01', 'YYYY-MM-DD'), 'DESPESA'
);

INSERT INTO TB_TRANSACOES (ID_USUARIO, ID_CATEGORIA, VL_VALOR, DS_DESCRICAO, DT_TRANSACAO, CD_TIPO)
VALUES (
    (SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com'),
    (SELECT ID_CATEGORIA FROM TB_CATEGORIAS WHERE DS_NOME = 'Alimentação'
        AND ID_USUARIO = (SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com')),
    520.00, 'Supermercado mensal',
    TO_DATE('2026-05-08', 'YYYY-MM-DD'), 'DESPESA'
);

INSERT INTO TB_TRANSACOES (ID_USUARIO, ID_CATEGORIA, VL_VALOR, DS_DESCRICAO, DT_TRANSACAO, CD_TIPO)
VALUES (
    (SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com'),
    (SELECT ID_CATEGORIA FROM TB_CATEGORIAS WHERE DS_NOME = 'Serviços'
        AND ID_USUARIO = (SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com')),
    230.00, 'Energia + Internet',
    TO_DATE('2026-05-10', 'YYYY-MM-DD'), 'DESPESA'
);

INSERT INTO TB_TRANSACOES (ID_USUARIO, ID_CATEGORIA, VL_VALOR, DS_DESCRICAO, DT_TRANSACAO, CD_TIPO)
VALUES (
    (SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com'),
    (SELECT ID_CATEGORIA FROM TB_CATEGORIAS WHERE DS_NOME = 'Transporte'
        AND ID_USUARIO = (SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com')),
    180.00, 'Combustível',
    TO_DATE('2026-05-15', 'YYYY-MM-DD'), 'DESPESA'
);

INSERT INTO TB_TRANSACOES (ID_USUARIO, ID_CATEGORIA, VL_VALOR, DS_DESCRICAO, DT_TRANSACAO, CD_TIPO)
VALUES (
    (SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com'),
    (SELECT ID_CATEGORIA FROM TB_CATEGORIAS WHERE DS_NOME = 'Saúde'
        AND ID_USUARIO = (SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com')),
    100.00, 'Academia',
    TO_DATE('2026-05-01', 'YYYY-MM-DD'), 'DESPESA'
);

INSERT INTO TB_TRANSACOES (ID_USUARIO, ID_CATEGORIA, VL_VALOR, DS_DESCRICAO, DT_TRANSACAO, CD_TIPO)
VALUES (
    (SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com'),
    (SELECT ID_CATEGORIA FROM TB_CATEGORIAS WHERE DS_NOME = 'Saúde'
        AND ID_USUARIO = (SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com')),
    87.50, 'Farmácia',
    TO_DATE('2026-05-18', 'YYYY-MM-DD'), 'DESPESA'
);

INSERT INTO TB_TRANSACOES (ID_USUARIO, ID_CATEGORIA, VL_VALOR, DS_DESCRICAO, DT_TRANSACAO, CD_TIPO)
VALUES (
    (SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com'),
    (SELECT ID_CATEGORIA FROM TB_CATEGORIAS WHERE DS_NOME = 'Lazer'
        AND ID_USUARIO = (SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com')),
    59.90, 'Streaming (Netflix + Spotify)',
    TO_DATE('2026-05-12', 'YYYY-MM-DD'), 'DESPESA'
);

INSERT INTO TB_TRANSACOES (ID_USUARIO, ID_CATEGORIA, VL_VALOR, DS_DESCRICAO, DT_TRANSACAO, CD_TIPO)
VALUES (
    (SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com'),
    (SELECT ID_CATEGORIA FROM TB_CATEGORIAS WHERE DS_NOME = 'Alimentação'
        AND ID_USUARIO = (SELECT ID_USUARIO FROM TB_USUARIOS WHERE DS_EMAIL = 'diego@pragfy.com')),
    145.00, 'Jantar aniversário',
    TO_DATE('2026-05-19', 'YYYY-MM-DD'), 'DESPESA'
);

-- ── Resumo esperado no dashboard ──────────────────────────────
-- Receitas:  R$  8.700,00
-- Despesas:  R$  3.122,40
-- Saldo:     R$  5.577,60
